### ISSUE TITLE
Can't Upload Data to an Ubuntu VPS using Ubuntu Firefox

### ISSUE THREAD

**Issue by radumas** [conveyal/analyst-server#116] opened 2015-07-06 19:07 UTC
Running Analyst Server on a Digital Ocean VPS running `Ubuntu 14.04` and trying to upload gtfs data or shapefile `.zip` from my laptop in `Ubuntu Firefox 38.0`, when I click on `Create` (for Create Bundle) or `Upload Shapefile` nothing happens. I get no indication an action has been recorded by the server, all it prints to terminal is
```shell
get status: 0 requests outstanding, 10 chunk size
got worker status: Status 0 queued items, chunk size 10 on graph null
```

The debug console in Firefox shows `ReferenceError: event is not defined` for `transport-data.js:134:0` and `spatial-data.js:104:0` respectively.

Possibly related to https://github.com/conveyal/analyst-server/issues/1

EDIT:
I've tried:  

1. Restarting the server
2. Creating a new project

**Comment by mattwigway** [comment] 2015-07-16 22:01
Yep, this is a known issue and a duplicate of #1. I haven't had a chance to look into it yet, I've just been using Chrome for analyst.

**Closed by mattwigway** 2015-07-16 22:01 UTC

**Comment by radumas** [comment] 2015-09-24 17:58
So now I have the exact same problem, but in Ubuntu Chromium.

In Ubuntu Firefox the `Create` button produces the following error output
```bash
13:56:11.026 [qtp423923188-28] INFO  com.conveyal.analyst.server.Routes - unhandled exception, caught by server thread
org.apache.commons.fileupload.FileUploadBase$InvalidContentTypeException: the request doesn't contain a multipart/form-data or multipart/mixed stream, content type header is application/x-www-form-urlencoded; charset=UTF-8
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.<init>(FileUploadBase.java:947) ~[analyst-server.jar:na]
	at org.apache.commons.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:310) ~[analyst-server.jar:na]
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:334) ~[analyst-server.jar:na]
	at org.apache.commons.fileupload.FileUploadBase.parseParameterMap(FileUploadBase.java:391) ~[analyst-server.jar:na]
	at org.apache.commons.fileupload.servlet.ServletFileUpload.parseParameterMap(ServletFileUpload.java:133) ~[analyst-server.jar:na]
	at com.conveyal.analyst.server.controllers.BundleController.createBundle(BundleController.java:59) ~[analyst-server.jar:na]
	at com.conveyal.analyst.server.Routes$$Lambda$27/1403700359.handle(Unknown Source) ~[na:na]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) ~[analyst-server.jar:na]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:159) ~[analyst-server.jar:na]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:60) [analyst-server.jar:na]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179) [analyst-server.jar:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [analyst-server.jar:na]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [analyst-server.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [analyst-server.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:451) [analyst-server.jar:na]
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252) [analyst-server.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266) [analyst-server.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240) [analyst-server.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596) [analyst-server.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527) [analyst-server.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45-internal]
```
